apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: retail-store-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carts
  template:
    metadata:
      labels:
        app: carts
    spec:
      containers:
      - name: carts
        image: public.ecr.aws/aws-containers/retail-store-sample-cart:0.7.0
        env:
        - name: REDIS_URL
          value: redis://redis:6379
        - name: DYNAMODB_ENDPOINT
          value: http://dynamodb-local:8000
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: carts
  namespace: retail-store-sample
spec:
  selector:
    app: carts
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
