apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: retail-store-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: public.ecr.aws/aws-containers/retail-store-sample-catalog:0.7.0
        env:
        - name: DB_ENDPOINT
          value: mysql:3306
        - name: DB_NAME
          value: catalog
        - name: DB_USER
          value: catalog
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: retail-store-sample
spec:
  selector:
    app: catalog
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
