apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: retail-store-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: public.ecr.aws/aws-containers/retail-store-sample-checkout:0.7.0
        env:
        - name: REDIS_URL
          value: redis://redis:6379
        - name: ENDPOINTS_ORDERS
          value: http://orders
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: retail-store-sample
spec:
  selector:
    app: checkout
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
