apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: retail-store-sample
data:
  mysql.conf: |
    [mysqld]
    default-authentication-plugin=mysql_native_password
    skip-name-resolve

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: retail-store-sample
type: Opaque
data:
  mysql-root-password: cm9vdA== # root
  mysql-password: Y2F0YWxvZw== # catalog

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: retail-store-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: catalog
        - name: MYSQL_USER
          value: catalog
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-config
        configMap:
          name: mysql-config
      - name: mysql-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: retail-store-sample
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
