apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: retail-store-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: public.ecr.aws/aws-containers/retail-store-sample-ui:0.7.0
        env:
        - name: ENDPOINTS_CATALOG
          value: http://catalog
        - name: ENDPOINTS_CARTS
          value: http://carts
        - name: ENDPOINTS_ORDERS
          value: http://orders
        - name: ENDPOINTS_CHECKOUT
          value: http://checkout
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: retail-store-sample
spec:
  selector:
    app: ui
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
